<a href="https://colab.research.google.com/github/hunnurjirao/Machine Learning with TensorFlow/blob/master/Introduction to TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tensors**

### Importing necessary modules

In [1]:
import numpy as np
import tensorflow as tf
print(tf.__version__)

tf.executing_eagerly() # Make sure that GPU is off to enable eager execution

2.2.0


True

### Fixed Tensors

In [2]:
num_rows = 2
num_cols = 3

zero_tensor = tf.zeros([num_rows,num_cols])
print("Zero tensor: " , zero_tensor)

Zero tensor:  tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [3]:
ones_tensor = tf.ones([num_rows,num_cols])
print("Ones tensor: ", ones_tensor)

Ones tensor:  tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [4]:
filled_tensor = tf.fill([num_rows,num_cols] , 6)
print("Filled tensor: ", filled_tensor)

Filled tensor:  tf.Tensor(
[[6 6 6]
 [6 6 6]], shape=(2, 3), dtype=int32)


In [5]:
const_tensor = tf.constant([1,2,3])
print("Constant tensor: ", const_tensor)

Constant tensor:  tf.Tensor([1 2 3], shape=(3,), dtype=int32)


### Tensors of similar shape

In [6]:
zeros_similar = tf.zeros_like(const_tensor)
print(zeros_similar)


tf.Tensor([0 0 0], shape=(3,), dtype=int32)


In [7]:
ones_similar = tf.ones_like(const_tensor)
print(ones_similar)

tf.Tensor([1 1 1], shape=(3,), dtype=int32)


### Sequence Tensors

In [8]:
lin_tensor = tf.linspace(start=0.0, stop=1.0,num=3)
print(lin_tensor)

tf.Tensor([0.  0.5 1. ], shape=(3,), dtype=float32)


In [9]:
lin_seq_tensor = tf.range(start=3, limit=20, delta=5)
print(lin_seq_tensor)

tf.Tensor([ 3  8 13 18], shape=(4,), dtype=int32)


### Random Tensors

In [10]:
Rand_tensor = tf.random_uniform_initializer(minval=0, maxval=1)
print(Rand_tensor)

# **Placeholders and Variables**

### Declaring and Initializing Variables:

In [11]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
tf.executing_eagerly()

sess = tf.Session()
x =tf.Variable(tf.zeros( [2,3]))
initializer = tf.global_variables_initializer ()
sess.run(initializer) 

Instructions for updating:
non-resource variables are not supported in the long term


### Declaring and Initializing Placeholders:

In [12]:
x = tf.placeholder(tf.float32, shape=[2,2])
y = tf.identity(x)
x_input = np.ones((2,2))
sess = tf.Session()
sess.run(y, feed_dict = {x : x_input}) 

array([[1., 1.],
       [1., 1.]], dtype=float32)

# **Working with Matrices**

In [13]:
identity_matrix = tf.diag([1.0, 1.0, 1.0])
A = tf.truncated_normal([2,3])
B =tf.fill([2,3],6.0)
D = tf.convert_to_tensor(np.array([[1,2,3],[3,5,6]]))

print("Identity matrix: ", sess.run(identity_matrix))

Identity matrix:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
print("A: ", sess.run(A))
print("B: ", sess.run(B))
print("D: ", sess.run(D))

A:  [[-0.27263048  0.99282235  0.7273219 ]
 [ 0.77289045  0.2679514   0.9819005 ]]
B:  [[6. 6. 6.]
 [6. 6. 6.]]
D:  [[1 2 3]
 [3 5 6]]


In [15]:
print("Addition: ", sess.run(A + B))

print("Subtraction: ", sess.run(A - B))

Addition:  [[6.3611197 5.5672097 6.027267 ]
 [5.5896864 6.329804  5.7682514]]
Subtraction:  [[-5.061139  -6.289337  -5.6101465]
 [-7.132176  -4.6845818 -5.031337 ]]


In [16]:
P = tf.constant([[1,2,3]])
Q = tf.constant([[1],[2],[3]])
print("Multiplication: ", sess.run(tf.matmul(P,Q))) 

print("transpose: ", sess.run(tf.transpose(P)))

Multiplication:  [[14]]
transpose:  [[1]
 [2]
 [3]]


# **Other Operations…**

In [17]:
print("Div: ", sess.run(tf.div(3,4)))

print("True div: ", sess.run(tf.truediv(3,4)))

print("Floor div: ", sess.run(tf.floordiv(3.0,4.0)))

print("mod: ", sess.run(tf.mod(22.0,5.0)))

Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
Div:  0
True div:  0.75
Floor div:  0.0
mod:  2.0
